### Packages download

In [16]:
# data processing libraries
#import numpy as np
import pandas as pd
import os

# webscraping annd HTML parsing libraries
import requests
import re
from bs4 import BeautifulSoup

# other libraries
import time
import nltk  
nltk.download("wordnet")  # only done once! we have to download the WordNet database locally

# very good tokenizer for english, considers sentence structure
from nltk.tokenize import TreebankWordTokenizer 
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer  
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from imblearn.over_sampling import SMOTE
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import NearMiss
from sklearn.model_selection import GridSearchCV
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import train_test_split


[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/elizavetabugaeva/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [17]:
#header for request
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"}

In [18]:
#gorillaz
url_gorillaz = 'https://www.lyrics.com/artist/Gorillaz'

Request html, save as txt

In [19]:
response=requests.get(url=url_gorillaz, headers=headers)

In [20]:
gorillaz_html = response.text

In [21]:
mkdir 'gorillaz'

mkdir: gorillaz: File exists


In [90]:
#save html as text on local computer
with open ('gorillaz/gorillaz_main.txt', 'w') as f:
    f.write(gorillaz_html)

In [22]:
#sample link to song: href="/lyric/32105073/David+Bowie/Boys+Keep+Swinging
song_pattern = '/lyric/+\d+\S*"'

Find all link extentions for each song


In [23]:
gorilazz_songs_ext= re.findall(song_pattern,gorillaz_html)

In [93]:
len(gorilazz_songs_ext)

910

Define function which will exlude all dupliates from the songs list


In [24]:
def clean_list(list):
    avoid = ['Version', 'Remastered', 'Live', 'DVD', 'RMX', 'Instrumental', 'Mix', 'Studio', '5D', 'Rmx','Soundtrack']
    return [elem for elem in list if not any(word in elem for word in avoid)]

In [25]:
g_songs_cleanedup= clean_list(gorilazz_songs_ext)

In [97]:
g_songs_cleanedup

['/lyric/36111152/Gorillaz/Dare"',
 '/lyric/36111191/Gorillaz/Feel+Good+Inc"',
 '/lyric/36037605/Gorillaz/Souk+Eye"',
 '/lyric/36084865/Gorillaz/Feel+Good+Inc"',
 '/lyric/36111106/Gorillaz/On+Melancholy+Hill"',
 '/lyric/36143656/Gorillaz/Feel+Good+Inc"',
 '/lyric/35162561/Gorillaz/Fire+Flies"',
 '/lyric/35086321/Gorillaz/Humility"',
 '/lyric/35085773/Gorillaz/Lake+Zurich"',
 '/lyric/35137952/Gorillaz/Sorcererz"',
 '/lyric/35303570/Gorillaz/Lake+Zurich"',
 '/lyric/35090436/Gorillaz/Humility"',
 '/lyric/35090435/Gorillaz/Tranz"',
 '/lyric/35090434/Gorillaz/Hollywood"',
 '/lyric/35090433/Gorillaz/Kansas"',
 '/lyric/35090431/Gorillaz/Idaho"',
 '/lyric/35090430/Gorillaz/Lake+Zurich"',
 '/lyric/35090429/Gorillaz/Magic+City"',
 '/lyric/35090428/Gorillaz/Fire+Flies"',
 '/lyric/35090427/Gorillaz/One+Percent"',
 '/lyric/35090426/Gorillaz/Souk+Eye"',
 '/lyric/35427533/Gorillaz/Tranz"',
 '/lyric/33874731/Gorillaz/Andromeda"',
 '/lyric/33874679/Gorillaz/Ascension"',
 '/lyric/33882615/Gorillaz/I+Swi

### Save txt files

In [26]:
def file_creator(songs_cleanedup,dir):
    seen_titles = set()
    for counter, link in enumerate(songs_cleanedup):
        url = 'https://www.lyrics.com' + link
        song_title = link.split('/')[4].rstrip("\"")
        if song_title not in seen_titles:
            response = requests.get(url, headers=headers)
            with open(f'{dir}/{song_title}.txt', 'w', encoding='utf-8') as f:
                f.write(response.text)
            print(counter, song_title, url)
            seen_titles.add(song_title)

In [28]:
file_creator(g_songs_cleanedup,'gorillaz')

0 Dare https://www.lyrics.com/lyric/36111152/Gorillaz/Dare"
1 Feel+Good+Inc https://www.lyrics.com/lyric/36111191/Gorillaz/Feel+Good+Inc"
2 Souk+Eye https://www.lyrics.com/lyric/36037605/Gorillaz/Souk+Eye"
4 On+Melancholy+Hill https://www.lyrics.com/lyric/36111106/Gorillaz/On+Melancholy+Hill"
6 Fire+Flies https://www.lyrics.com/lyric/35162561/Gorillaz/Fire+Flies"


KeyboardInterrupt: 

Save txt Nirvana

In [4]:
nivrana_url = 'https://www.lyrics.com/artist/Nirvana/'

In [ ]:
rn = requests.get(nivrana_url, headers=headers)

In [ ]:
mkdir 'nirvana'

In [ ]:
nirvana_html = rn.text

In [ ]:
with open ('nirvana/nirvana_main.txt', 'w') as f:
    f.write(nirvana_html)

In [ ]:
n_songs_ext = re.findall(song_pattern, nirvana_html)

In [ ]:
nirvana_clean = clean_list(n_songs_ext)
len(nirvana_clean)

In [ ]:
file_creator(nirvana_clean, 'nirvana')

### Create lists of lines out of the created txt files

In [103]:
def get_all_lines(dir_path, all_lines):
    all_lines = []
    for filename in os.listdir(dir_path):
        if filename.endswith('.txt'):
            file_path = os.path.join(dir_path, filename)
            with open(file_path, 'r', encoding='utf-8') as f: 
                file_soup = BeautifulSoup(f, 'html.parser')
                lyrics_elem = file_soup.find('pre', class_="lyric-body")
                if lyrics_elem is not None:
                    for line in lyrics_elem.get_text().split('\n'):
                        line = line.strip("\r")  # remove carriage return
                        if len(line) > 0:
                            all_lines.append(line)
    return all_lines


In [14]:
# Path to directory holding HTML files
nirvana_path = "/Users/elizavetabugaeva/Documents/Spiced/weekly_milestones/week_04/nirvana"
gorillaz_path = "/Users/elizavetabugaeva/Documents/Spiced/weekly_milestones/week_04/gorillaz"

In [ ]:
all_lines_gorillaz = []
gorillaz_func_lines = get_all_lines(gorillaz_path, all_lines_gorillaz)
all_lines_nirvana = []
nirvana_func_lines = get_all_lines(nirvana_path,all_lines_nirvana)

In [109]:
#Total corpus and labels: 
CORPUS = gorillaz_func_lines+nirvana_func_lines


In [110]:
LABELS = ['gorillaz'] * len(gorillaz_func_lines) + ['nirvana']* len(nirvana_func_lines)

In [111]:
d = {'song': CORPUS, 'artist': LABELS}
d

{'song': ['We got the power to be loving each other',
  'No matter what happens ',
  "We've got the power to do that",
  "On a le pouvoir de s'aimer, okay?",
  'We got the power to be ringing the great bell out there above us',
  'We got the power for that',
  'We got the power to do that',
  'And, we dream of home, I dream of life out of here',
  'Their dreams are small',
  "My dreams don't know fear (I got all you)",
  'I got my heart full of hope',
  'I will change everything',
  "No matter what I'm told",
  'How impossible it seems (we got the power)',
  'We did it before',
  "And we'll do it again",
  "We're indestructible",
  "Even when we're tired",
  "And we've been here before",
  'Just you and I',
  "Don't try to rescue me",
  "I don't need to be rescued",
  'We got the power to be loving each other',
  'No matter what happens ',
  "We've got the power to do that",
  "On a le pouvoir de s'aimer, okay?",
  'We got the power to be ringing the great bell out there above us',
  '

In [112]:
df = pd.DataFrame(d)
df.to_csv('gorillaz_nirvana.csv') 

### Vectorise text with Bag of words

Use the CountVectorizer from Scikit to transform your corpus into a matrix.


In [113]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(
    lowercase = True, 
    analyzer = 'word',
    stop_words = 'english',
    token_pattern = r"(?u)\b\w\w+\b",
    ngram_range = (1, 1)
)

In [114]:
vec = count_vectorizer.fit_transform(CORPUS)

In [118]:
count_matrix_skl = pd.DataFrame(
    vec.todense(), 
     columns=count_vectorizer.get_feature_names(),
    index=LABELS
)

/Users/elizavetabugaeva/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [119]:
count_matrix_skl

1975  21  24  2d  2pac  3x  62  75  800  911  ...  zapper  zip  \
gorillaz     0   0   0   0     0   0   0   0    0    0  ...       0    0   
gorillaz     0   0   0   0     0   0   0   0    0    0  ...       0    0   
gorillaz     0   0   0   0     0   0   0   0    0    0  ...       0    0   
gorillaz     0   0   0   0     0   0   0   0    0    0  ...       0    0   
gorillaz     0   0   0   0     0   0   0   0    0    0  ...       0    0   
...        ...  ..  ..  ..   ...  ..  ..  ..  ...  ...  ...     ...  ...   
nirvana      0   0   0   0     0   0   0   0    0    0  ...       0    0   
nirvana      0   0   0   0     0   0   0   0    0    0  ...       0    0   
nirvana      0   0   0   0     0   0   0   0    0    0  ...       0    0   
nirvana      0   0   0   0     0   0   0   0    0    0  ...       0    0   
nirvana      0   0   0   0     0   0   0   0    0    0  ...       0    0   

          zombie  zone  zzzz  zürich  él  いい感じ  ちょっと臭い  会いたい自分  
gorillaz       0     0     0       0   0     0       0       0  
gorillaz       0     0     0       0   0     0       0       0  
gorillaz       0     0     0       0   0     0       0       0  
gorillaz       0     0     0       0   0     0       0       0  
gorillaz       0     0     0       0   0     0       0       0  
...          ...   ...   ...     ...  ..   ...     ...     ...  
nirvana        0     0     0       0   0     0       0       0  
nirvana        0     0     0       0   0     0       0       0  
nirvana        0     0     0       0   0     0       0       0  
nirvana        0     0     0       0   0     0       0       0  
nirvana        0     0     0       0   0     0       0       0  

[8750 rows x 3957 columns]

Normalize the counts using the TfidfTransformer.


In [121]:
tf = TfidfTransformer(use_idf=True)

In [122]:
vec2 = tf.fit_transform(vec)

In [123]:
type(vec2)

scipy.sparse._csr.csr_matrix

In [125]:
print(vec2)

  (0, 2611)	0.5993332101349993
  (0, 2052)	0.6833168285991783
  (0, 1500)	0.41698658849228937
  (1, 2116)	0.6763142028958217
  (1, 1589)	0.7366132628193639
  (2, 3723)	0.5312893218172345
  (2, 2611)	0.6954308763269986
  (2, 1500)	0.48384662112496546
  (3, 2609)	0.5350574162737949
  (3, 2375)	0.4301009027236666
  (3, 1928)	0.49238230680753464
  (3, 55)	0.5350574162737949
  (4, 2843)	0.5126249943886373
  (4, 2611)	0.41281453305969046
  (4, 1519)	0.47066158317250484
  (4, 1500)	0.2872160609651912
  (4, 291)	0.5126249943886373
  (5, 2611)	0.820867229227251
  (5, 1500)	0.5711190698801569
  (6, 2611)	0.820867229227251
  (6, 1500)	0.5711190698801569
  (7, 1970)	0.3790138526388147
  (7, 1679)	0.39513977651451787
  (7, 1039)	0.8367873424735461
  (8, 3172)	0.7669574210644474
  :	:
  (8735, 1296)	0.6080042470732873
  (8735, 595)	0.5105503609651943
  (8735, 110)	0.6080042470732873
  (8736, 3478)	0.5303136945944672
  (8736, 3130)	0.45866098245566084
  (8736, 2482)	0.5403675729295208
  (8736, 1050)	

In [126]:
type(vec2.todense())

numpy.matrix

In [127]:
print(vec2.todense())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [128]:
# for us to see the vectorized labeled data
feature_matrix = pd.DataFrame(
    vec2.todense(), 
    columns=count_vectorizer.get_feature_names(), 
    index=LABELS
)

/Users/elizavetabugaeva/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


###Feature matrix - our dataset for train/test

In [129]:
feature_matrix

1975   21   24   2d  2pac   3x   62   75  800  911  ...  zapper  \
gorillaz   0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...     0.0   
gorillaz   0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...     0.0   
gorillaz   0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...     0.0   
gorillaz   0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...     0.0   
gorillaz   0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...     0.0   
...        ...  ...  ...  ...   ...  ...  ...  ...  ...  ...  ...     ...   
nirvana    0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...     0.0   
nirvana    0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...     0.0   
nirvana    0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...     0.0   
nirvana    0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...     0.0   
nirvana    0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...     0.0   

          zip  zombie  zone  zzzz  zürich   él  いい感じ  ちょっと臭い  会いたい自分  
gorillaz  0.0     0.0   0.0   0.0     0.0  0.0   0.0     0.0     0.0  
gorillaz  0.0     0.0   0.0   0.0     0.0  0.0   0.0     0.0     0.0  
gorillaz  0.0     0.0   0.0   0.0     0.0  0.0   0.0     0.0     0.0  
gorillaz  0.0     0.0   0.0   0.0     0.0  0.0   0.0     0.0     0.0  
gorillaz  0.0     0.0   0.0   0.0     0.0  0.0   0.0     0.0     0.0  
...       ...     ...   ...   ...     ...  ...   ...     ...     ...  
nirvana   0.0     0.0   0.0   0.0     0.0  0.0   0.0     0.0     0.0  
nirvana   0.0     0.0   0.0   0.0     0.0  0.0   0.0     0.0     0.0  
nirvana   0.0     0.0   0.0   0.0     0.0  0.0   0.0     0.0     0.0  
nirvana   0.0     0.0   0.0   0.0     0.0  0.0   0.0     0.0     0.0  
nirvana   0.0     0.0   0.0   0.0     0.0  0.0   0.0     0.0     0.0  

[8750 rows x 3957 columns]

In [ ]:
feature_matrix= feature_matrix.reset_index()
X = feature_matrix.drop('index', axis =1)
y = feature_matrix['index']

In [138]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### Fitting NB and log reg models

In [ ]:
NBmodel = MultinomialNB()

In [139]:
NBmodel.fit(X_train, y_train)  # model.fit

MultinomialNB()

In [140]:
print(f'train {NBmodel.score(X_train,y_train)}, test {NBmodel.score(X_test,y_test)}')

0.8713749573524394

In [ ]:
y_train.value_counts(normalize=True) #see if any class imbalance is present

gorillaz    0.637496
nirvana     0.362504
Name: index, dtype: float64

In [ ]:

lr_pipeline = Pipeline([
    ('PCA', PCA(n_components=0.99, svd_solver='full')),
    ('over', SMOTE(sampling_strategy={'nirvana':3500})),
    ('logregmodel', LogisticRegression(class_weight='balanced'))
])


In [ ]:
lr_pipeline.fit(X_train,y_train)

Pipeline(steps=[('PCA', PCA(n_components=0.99, svd_solver='full')),
                ('logregmodel', LogisticRegression(class_weight='balanced'))])

In [3]:
print(lr_pipeline.score(X_train,y_train), lr_pipeline.score(X_test_f,y_test_f))

NameError: name 'lr_pipeline' is not defined

### Using voting classifier to get best result of both

In [ ]:
models = [('logreg', LogisticRegression()),('NBmodel', MultinomialNB())]

In [ ]:
voting_pipeline = Pipeline([
    ('voting', VotingClassifier(models))
])

In [ ]:
voting_pipeline.fit(X_train_f,y_train_f)

Pipeline(steps=[('voting',
                 VotingClassifier(estimators=[('logreg', LogisticRegression()),
                                              ('NBmodel', MultinomialNB())]))])

In [ ]:
print(f'train {voting_pipeline.score(X_train_f,y_train_f)}, test {voting_pipeline.score(X_test_f,y_test_f)}')

train 0.8522688502217673, test 0.7974376731301939
